/*
 Copyright (c) 2005-2018 Oracle and/or its affiliates. Contains software licensed under the MIT license. Removal of this notice is prohibited. Full attribution and licensing at: http://ccexperimentsstatic.oracleoutsourcing.com/api/license.html 
*/
(function(){var C=window.ATGSvcs||{};if(!C.REC_VERSION){C.CFG||(C.CFG={});var Gb=function(){var a=null,b=function(a,b,c){var d="object"===typeof a?a:{complete:c||!c&&b||K(a)&&a,duration:a,easing:c&&b||b&&!K(b)&&b};d.old=d.complete;d.complete=function(){K(d.old)&&d.old.call(this)};return d},c={linear:function(a,b,d,c){return d+c*a},swing:function(a,b,d,c){return(-Math.cos(a*Math.PI)/2+.5)*c+d}},d=[],e=function(a,b,d){this.options=b;this.elem=a;this.prop=d;b.orig||(b.orig={})},f={opacity:function(a){N(a.elem,
"opacity",a.now)},_default:function(a){a.elem.style&&null!=a.elem.style[a.prop]?a.elem.style[a.prop]=a.now+a.unit:a.elem[a.prop]=a.now}};e.prototype={update:function(){this.options.step&&this.options.step.call(this.elem,this.now,this);(f[this.prop]||f._default)(this);"height"!=this.prop&&"width"!=this.prop||!this.elem.style||(this.elem.style.display="block")},cur:function(a){return null==this.elem[this.prop]||this.elem.style&&null!=this.elem.style[this.prop]?(a=parseFloat(N(this.elem,this.prop,a)))&&
-1E4<a?a:parseFloat(N(this.elem,this.prop))||0:this.elem[this.prop]},custom:function(b,c,e){function f(a){return g.step(a)}this.startTime=+new Date;this.start=b;this.end=c;this.unit=e||this.unit||"px";this.now=this.start;this.pos=this.state=0;var g=this;f.elem=this.elem;f()&&d.push(f)&&!a&&(a=setInterval(function(){for(var b=0;b<d.length;b++)d[b]()||d.splice(b--,1);d.length||(clearInterval(a),a=n)},13))},step:function(a){var b=+new Date;if(a||b>=this.options.duration+this.startTime){this.now=this.end;
this.pos=this.state=1;this.update();a=this.options.curAnim[this.prop]=!0;for(var d in this.options.curAnim)!0!==this.options.curAnim[d]&&(a=!1);if(a){null!=this.options.display&&(this.elem.style.overflow=this.options.overflow,this.elem.style.display=this.options.display,"none"==N(this.elem,"display")&&(this.elem.style.display="block"));if(this.options.hide||this.options.show)for(var e in this.options.curAnim)N(this.elem,e,this.options.orig[e]);this.options.complete.call(this.elem)}return!1}d=b-this.startTime;
this.state=d/this.options.duration;this.pos=c[this.options.easing||(c.swing?"swing":"linear")](this.state,d,0,1,this.options.duration);this.now=this.start+(this.end-this.start)*this.pos;this.update();return!0}};return function(a,d,c,f,q){var g=b(c,f,q);a.length||(a=[a]);return p(a,function(){var a=ra({},g),b,c=this;for(b in d)"height"!=b&&"width"!=b||!this.style||(a.display=N(this,"display"),a.overflow=this.style.overflow);null!=a.overflow&&(this.style.overflow="hidden");a.curAnim=ra({},d);p(d,function(b,
d){var f=new e(c,a,b),g=d.toString().match(/^([+-]=)?([\d+-.]+)(.*)$/),h=f.cur(!0)||0;if(g){d=parseFloat(g[2]);var v=g[3]||"px";"px"!=v&&(c.style[b]=(d||1)+v,h*=(d||1)/f.cur(!0),c.style[b]=h+v);g[1]&&(d=("-="==g[1]?-1:1)*d+h);f.custom(h,d,v)}else f.custom(h,d,"")});return!0})}}(),u={match:function(a){var b=document.cookie.split(/; ?/),c=0;for(6!=w(a)&&(a=H(a));c<b.length;){var d=b[c++].split("=");if(~d[0].search(a)){var e=e||{};e[d[0]]=t(d[1])?decodeURIComponent(d[1]):""}}return e},has:function(a){a=
u.get(a);return!!a||""===a},get:function(a){var b=u.match(6==w(a)?a:"^"+a+"$");if(b)return b[a]||""},set:function(a,b,c){var d="; path=/",e=location.hostname,f=e.split("."),g=f.length;/^(\d{1,3}\.){3}\d{1,3}$/.test(e)||(e=(size=2<g&&/^(COM|EDU|NET|ORG|GOV|MIL|INT)$/i.test(f[g-1])?-2:3<g?-3:0)?"."+f.slice(size).join("."):1==g?0:e);d+=e?"; domain="+e:"";if(!0===c)var k="Fri, 01 Jan 2038 00:00:00 GMT";else c!==n&&(k=new Date,k.setTime(+k+36E5*c),k=k.toGMTString());k&&(d+="; expires="+k);document.cookie=
a+"="+Ca(b)+d}},N=function(){var a=function(a,b,d){var c={},e;for(e in b)c[e]=a.style[e],a.style[e]=b[e];d.call(a);for(e in b)a.style[e]=c[e]},b=/z-?index|font-?weight|opacity|zoom|line-?height/i,c=/opacity=([^)]*)/,d=function(b,d,c,f){if("width"==d||"height"==d){c=function(){g="width"==d?b.offsetWidth:b.offsetHeight;"border"!==f&&p(k,function(){f||(g-=parseFloat(e(b,"padding"+this,!0))||0);g="margin"===f?g+(parseFloat(e(b,"margin"+this,!0))||0):g-(parseFloat(e(b,"border"+this+"Width",!0))||0)})};
var g,h={position:"absolute",visibility:"hidden",display:"block"},k="width"==d?["Left","Right"]:["Top","Bottom"];0!==b.offsetWidth?c():a(b,h,c);return Math.max(0,Math.round(g))}return e(b,d,c)},e=function(a,b,d){k||q();var e=a.style;if("opacity"==b&&!m.opacity&&a.currentStyle){var f=c.test(a.currentStyle.filter||"")?parseFloat(RegExp.$1)/100+"":"";return""==f?"1":f}b.match(/float/i)&&(b=h.styleFloat);!d&&e&&e[b]?f=e[b]:Hb.getComputedStyle?(b.match(/float/i)&&(b="float"),b=b.replace(/([A-Z])/g,"-$1").toLowerCase(),
(a=Hb.getComputedStyle(a,null))&&(f=a.getPropertyValue(b)),"opacity"==b&&""==f&&(f="1")):a.currentStyle&&(f=b.replace(/\-(\w)/g,function(a,b){return b.toUpperCase()}),f=a.currentStyle[b]||a.currentStyle[f],!/^\d+(px)?$/i.test(f)&&/^\d/.test(f)&&(b=e.left,d=a.runtimeStyle.left,a.runtimeStyle.left=a.currentStyle.left,e.left=f||0,f=e.pixelLeft+"px",e.left=b,a.runtimeStyle.left=d));return f},f=function(a,d,c){var e=d,f;if(("width"==d||"height"==d)&&0>parseFloat(c))return a;"string"===typeof d&&(e={},
e[d]=c);for(f in e)e.hasOwnProperty(f)&&(c=e[f],"number"!==typeof c||b.test(f)||(c+="px"),g(a.style,f,c));return a},g=function(a,b,d){k||q();b=h[b]||b;m.opacity||"opacity"!=b?(b=b.replace(/-([a-z])/ig,function(a,b){return b.toUpperCase()}),a[b]=d):(a.zoom=1,a.filter=(a.filter||"").replace(/alpha\([^)]*\)/,"")+("NaN"==parseInt(d)+""?"":"alpha(opacity="+100*d+")"))},k=!1,m={},h={},q=function(){if(!k){var a=document.createElement("div");a.style.display="none";a.innerHTML='<a href="/a" style="float:left;opacity:.5;">a</a>';
a=a.getElementsByTagName("a")[0];var b=a.style.cssFloat?"cssFloat":"styleFloat";m={opacity:"0.5"===a.style.opacity,cssFloat:!!a.style.cssFloat};h["float"]=b;h.cssFloat=b;h.styleFloat=b;k=!0}};window.setTimeout(q,0);return function(){return"object"===typeof arguments[1]||arguments[2]!==n&&"boolean"!==typeof arguments[2]?f.apply(this,arguments):d.apply(this,arguments)}}(),Da=[],Ib=function(){},I={create:function(a,b){a=document.createElement(a);var c=b[0]||{},d=1,e,f;b[0]&&(b[0].constructor!=Object||
b[0].tagName)&&(c={},d=0);for(e in c)switch(e){case "Class":case "class":a.className=c[e];break;case "style":a.style.cssText=c[e];break;default:a[e]=c[e]}for(;d<b.length;d++)if(e=b[d])for(e.constructor!=Array&&(e=[e]),c=0;c<e.length;c++)if(f=e[c]){if("number"==typeof f||"string"==typeof f)f=document.createTextNode(""+f);a.appendChild(f)}return a},tag:function(a){a&&!I[a]&&(I[a]=function(){return I.create(a,arguments)})},tags:function(a){a=a.split(/\|/);for(var b=0;b<a.length;b++)I.tag(a[b])}},Za=
[],sa=function(a,b,c,d){Za.push([a,b,c,d]);Jb(a,b,c,d)},Jb=function(a,b,c,d){var e=(d||"")+b+c;a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&(a["e"+e]=c,a[e]=function(){a["e"+e](window.event)},a.attachEvent("on"+b,a[e]))},$a=function(a,b,c,d){d=(d||"")+b+c;a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&(a.detachEvent("on"+b,a[d]),a[d]=a["e"+d]=null)},r={E:{},W:[],B:{},occur:function(a){a=[].concat(a);for(var b=0,c=0;b<a.length;){var d=a[b++],e=1<arguments.length?
[].slice.call(arguments,1):[],f=r.E,g=r.W,k=r.B[d]||[],m=k.length,h,q={type:d,ergCount:f[d],ergStamp:+new Date};f[d]=f[d]?f[d]+1:1;for(h=0;h<g.length;){var A=g[h][0];var v=g[h][1];r.gate(A)?(g.splice(h,1),v[0].apply(A,v[1])):h++}for(;m--;)q.data=k[m][1],k[m][0].apply(null,[q].concat(e));c+=f[d]}return c},gate:function(a){var b=r.E,c;for(c in a)if(a.hasOwnProperty(c)&&(!0===a[c]?!b[c]:!(0<b[c]-a[c])))return!1;return!0},cond:function(a,b){var c=r.E;return b&&!0!==b?0<c[a]-b:c[a]},wait:function(a,b){r.W.push([a,
[b,[].slice.call(arguments,2)]])},bind:function(a,b,c){var d=!1;c=c||{};a=r.B[a]=r.B[a]||[];for(var e=a.length;e--;)d=d||a[e][0]===b;d||a.push([b,c])},unbind:function(a,b){for(var c=r.B[a]||[],d=c.length;d--;)c[d][0]===b&&c.splice(d,1);c.length||delete r.B[a]}},ab=function(a){aa(a)&&p(a,function(a,c){K(c)&&r.bind(a,c)})},ta=function(){var a=Array.prototype.slice,b=document.createElement("div"),c={};try{a.call(b.childNodes)}catch(D){a=function(a){for(var b=[],d=this.length;a<d;)b[a]=this[a++];return b}}if(b.querySelectorAll)return b=
null,function(b,d){return a.call((d||document).querySelectorAll(b),0)};b.className="x";b.getAttribute("className")&&(c={"class":"className"});var d=/^#[a-zA-Z0-9_\-]+$/,e=/^(\*|[a-zA-Z0-9]+)$/,f=/^\.[a-zA-Z0-9_\-]+$/,g=/^(\*|[a-zA-Z0-9]+)\.[a-zA-Z0-9_\-]+$/,k=/^(\*|[a-zA-Z0-9]+)\[(.+)\]+$/,m=/[^>|\+|\-|\*|~|\]|\w]*(>|\s)+(?!\+|\-|\*|~)/,h=function(b,c,Fb){b=b.replace(/^\s+|\s+$/g,"");var D=b.match(m),n=[],G=[],ea;if(D){D=D[0];var Ea=b.indexOf(D);var E=b.substr(0,Ea)}else E=b;d.test(E)?(E=q(E.substring(1),
c))&&n.push(E):e.test(E)?n.push.apply(n,a.call(c.getElementsByTagName(E),0)):f.test(E)?n.push.apply(n,A(E.substring(1),c)):g.test(E)?n.push.apply(n,v(E,c)):(ea=E.match(k))&&n.push.apply(n,l(ea[1],ea[2],c));if(Ea)for(ea=n.length,E=b.substr(Ea+D.length);ea;)G=G.concat(h(E,n[--ea],~D.indexOf(">")));else G=n;if(Ea||Fb)G=p(G,Fb?c:"");return G},q=b.all?function(a,b){for(var d=b=b.all[a],c=0;d;){if(d.id==a)return d;d=b[c++]}return null}:function(a,b){return"undefined"!==typeof b.getElementById?b.getElementById(a):
(a=document.getElementById(a))?a.compareDocumentPosition(b)&8?a:null:null},A=b.getElementsByClassName?function(b,d){return a.call(d.getElementsByClassName(b),0)}:function(a,b){return v("*."+a,b)},v=function(a,b){a=a.split(".");for(var d=b.getElementsByTagName(a.shift()),c=new RegExp("(?:\\s|^)"+a.shift()+"(?:\\s|$)"),e=d.length,f=0,g=0;f<e;++f)b=d[f],c.test(b.className)&&(a[g++]=b);return a},l=function(a,b,d){a=d.getElementsByTagName(a);var e=b.match(/([^~\|=]*)(~|\|)*=*(.*)/);b=a.length;d=[];var f=
e[1],g=e[2];e=e[3];var h;e=g?"~|".indexOf(g)?"^"+e+"-*":"(?:\\s|^)"+e+"(?:\\s|$)":"^"+(e||".*")+"$";for(f=c[f]||f;b;)g=a[--b],(h=g.getAttribute(f,0))&&~h.search(e)&&d.push(g);return d},p=b.uniqueID?function(a,b){for(var d=[],c={},e=a.length,f=0,g;e;)g=a[--e],c[g.uniqueID]||b&&g.parentNode!=b||(d[f++]=g,c[g.uniqueID]=1);return d}:function(a,b){for(var d=[],c=a.length,e=0,f=0,g;e<c;e++)g=a[e],g[975864012]||b&&g.parentNode!=b||(d[f++]=g,g[975864012]=1);for(e=0;e<f;e++)delete d[e][975864012];return d};
b=null;return function(a,b){b=b||document;a=a.split(/\s*,\s*/);for(var d=a.length,c=[];d;)c=c.concat(h(a[--d],b));return c}}(),bb=Object.prototype.toString,cb=navigator.userAgent.toLowerCase(),Ca=window.encodeURIComponent,n,Kb=cb.match(/msie (\d+)/)?+RegExp.$1:0,sc=cb.match(/ (edge\/|trident.*rv:)(\d+)/)?+RegExp.$2:Kb,H=function(a){return(a||"").replace(/^\s+|\s+$/g,"")},K=function(a){return"[object Function]"===bb.call(a)},B=function(a){return"[object Array]"===bb.call(a)},Hb=document.defaultView||
{},p=function(a,b,c){var d,e=0,f=a.length;if(c)if(f===n)for(d in a){if(a.hasOwnProperty(d)&&!1===b.apply(a[d],c))break}else for(;e<f&&!1!==b.apply(a[e++],c););else if(f===n)for(d in a){if(a.hasOwnProperty(d)&&!1===b.call(a[d],d,a[d]))break}else for(c=a[0];e<f&&!1!==b.call(c,e,c);c=a[++e]);return a},ra=function(){var a=arguments[0]||{},b=1,c=arguments.length,d=!1,e;"boolean"===typeof a&&(d=a,a=arguments[1]||{},b=2);"object"===typeof a||K(a)||(a={});c==b&&(a=l,--b);for(;b<c;b++)if(null!=(e=arguments[b]))for(var f in e){var g=
a[f],k=e[f];a!==k&&(d&&k&&"object"===typeof k&&!k.nodeType?a[f]=ra(d,g||(null!=k.length?[]:{}),k):k!==n&&(a[f]=k))}return a},db=/gomezagent/.test(cb),Lb=function(a,b){if(!a||"object"!=typeof a)return a;var c=a.constructor===Array?[]:{};p(a,function(a,e){isNaN(a)&&b&&"-"==a.charAt(0)||(c[a]=Lb(e,b))});return c},eb=function(a,b,c,d){var e=[],f,g=6==w(a),k=g?"r":d.compare||"=";"="==k&&(/^("|').*\1$/.test(a)&&(a=a.slice(1,-1)),"id"==c&&(a=a.replace(/^#/,"")));p(ta(b),function(b,h){f=h.getAttribute(c)||
"";d.trim&&(f=H(f));g||d["case"]||(f=R(f));fa(f,a,k)&&e.push(h)});return e},Mb=function(){var a=arguments,b=a.length,c,d=0;if(1==b)var e=a[0];else for(e={};d<b;)(c=a[d++])&&(e[c]=a[d++]);e&&ra(!0,l.CFG,e)},Nb=function(a,b){return a.replace(/^([^/:]*:?\/\/)*([^\/]+[^\.])\//,function(a,d,e){return(b?"https:":document.location.protocol)+"//"+e+"/"})},Ob=function(a,b){return(b&&2!==b?x("-exp-host","ccrules.oracleoutsourcing.com"):x("-rules-host","rules.atgsvcs.com"))+"/"+x("-rules-base-path","EERules/")+
a+"/3.0/json/"+(b?y:z)},tc=function(a){return Fa(a,2)},Pb=function(a){return Fa(a,1)},Fa=function(a,b){var c=U?O:J(),d=U?S:fb();return Ob(a,b)+(c?"/"+c:"")+(d?"?sessionId="+d+"&E3SessionID="+d:"")},Ga=function(a,b){var c,d=[],e;b=b?b+".":"";p(a,function(a,g){if(null!=g){e=b+a;if(B(g))if((c=g.length)&&aa(g[0]))g=Ga(uc(g),e);else{for(;c--;)g[c]=Ca(g[c].replace(/(,|\\)/g,"\\$1"));g=e+"="+g.join(",")}else g=aa(g)?Ga(g,e):e+"="+Ca(""+g);g&&d.push(g)}});return d.join("&")},uc=function(a){var b={},c,d,e=
a.length;e&&(p(a,function(a,d){p(d,function(a){b[a]=[]})}),p(b,function(b,g){for(c=0;c<e;c++)d=a[c][b],g.push(d==n?"":""+d)}));return b},gb=function(a,b,c){a=Nb(a,c);b&&(a+=(~a.indexOf("?")?"&":"?")+Ga(b));return a},ha=function(a,b,c){a=gb(a,b);c=I.SCRIPT({charset:x("charset","utf-8"),src:c?a.replace(/^http:/i,"https:"):a});Qb(c)},ua=function(a,b){return"https://"+(b?x("-exp-static-host","ccexperimentsstatic.oracleoutsourcing.com"):x("-static-host","ccexperimentsstatic.oracleoutsourcing.com"))+"/"+
a},Ha=function(a,b){var c=[],d=[],e=function(){var a={};p(l.CFG,function(b,d){"object"!=typeof d&&(a[b]=d)});return a}(),f=function(a){var b=0,c;if(a)try{for(;b<d.length;b++)if(c=a[d[b][1]])d[b][0](c)}catch(h){y&&P(h,"callback",2,n,1)}};this.addResource=function(a,b){hb(a,c)||c.push(a);ra(!0,e,b);r.occur(a)};this.addCallback=function(a,b){d.push([a,b])};this.send=function(b){var d=Nb(a(c.join("/")),b);b=x("charset","utf-8");var g=window,h=g.JSON,q,A=this,v=Lb(e,1);v.uoid=this.exp?y:z;if(g.XMLHttpRequest&&
h&&h.stringify&&h.parse&&!sc){var l=new XMLHttpRequest;if("withCredentials"in l){g=g.Prototype&&K(Object.toJSON)?Object.toJSON(v):h.stringify(v);l.open("POST",d,!0);g=Ca(g);if(d=V(x("-eeTimeout")))l.exp=this.exp,l.timeout=d,l.ontimeout=function(){this.exp?(W=[],ba={},Rb(-1)):X=[];ia()};l.onreadystatechange=function(){q=H(this.responseText);if(4==this.readyState&&200==this.status&&q)try{f(h.parse(q))}catch(rc){P(rc,"callback",2,n,A.exp)}};l.withCredentials=!0;l.setRequestHeader("Content-Type","application/x-www-form-urlencoded;charset="+
b);l.send(g);return}}v.callback=vc(f);ha(d,v)};1===b?this.exp=1:this.addCallback(Sb,"tracking")},Tb,va,ib,Ia,F,Ub,Wb=function(){if(!Ja&&Ka()&&S&&!Ub){var a=window._eeq;window._eeq=Vb;Ub=1;B(a)&&p(a,function(a,c){Vb.push(c)})}},Xb=function(){F=window.OracleUnifiedVisit;if(U&&!ib&&F&&F.VERSION){var a=F.accountId,b=x("-sf-eeid")||F.eeid||(window._ATGSvcs||{}).eeid;if(a&&!y){wa(a);var c=1}z&&!y&&(wa(z),c=1);b&&(ja(b),c=1);y&&z&&0==y.indexOf(z)&&(y=z);z==y&&(ja(),wa(y));c&&(x("-exp-host")||(l.CFG["-exp-host"]=
x("-rules-host")),x("-exp-static-host")||(l.CFG["-exp-static-host"]=x("-static-host")));a=Ka();c=jb();a&&c&&(kb(a),u.set(ka,a,!0),S=c);Wb();ib=1}},ma=function(){if(!La&&(Xb(),ib)){La=1;r.occur("ready");var a=l.setupFn||C.setupFn;if(K(a))try{a()}catch(b){P(b,"setup",2)}U?xa(O)||!z&&!y||Ma():xa(O)&&z?Tb||(Tb=1,ha(Ob("xd")+"/xd.js",n,la())):(J()||J(O),Ma());!db&&z&&r.occur(["estara_ready","webcare_ready"]);y&&u.has(lb)&&ha(ua("js/eeExp.js",1),n,1)}},ac=function(){if(z&&!u.has(mb)&&!nb){nb=1;var a=new Ha(Fa);
r.occur(["plato_ready","eeReady"]);a.addResource("view",{view:{referrer:document.referrer||n,pageTitle:document.title||n}});a.addResource("rules",{rules:{estaraFsGuid:ob(),locHash:location.hash||n,spa:x("-eeSPA")||U?1:n,debug:u.get(Yb),ip:u.get(Zb)}});a.addCallback(pb,"donotcall");a.addCallback(qb,"configuration");a.addCallback($b,"invites");a.addCallback(rb,"ab");a.addCallback(sb,"rules");a.send(la())}},Ma=function(){if(La&&!va&&(va=1,!db&&(ac(),y))){var a=new Ha(Pb,1);r.occur("expReady");a.addResource("view",
{view:{referrer:document.referrer||n,pageTitle:document.title||n}});a.addResource("rules",{rules:{locHash:location.hash||n,noExperiments:Ja,spa:""+document.location}});a.addCallback(bc,"configuration");a.addCallback(cc,"ab");a.addCallback(dc,"topics");a.addCallback(ec,"rules");a.send(la())}},La=!1,wc=function(){document.addEventListener?document.addEventListener("DOMContentLoaded",function(){document.removeEventListener("DOMContentLoaded",arguments.callee,!1);ma()},!1):document.attachEvent&&"complete"!=
document.readyState&&(document.attachEvent("onreadystatechange",function(){"complete"==document.readyState&&(document.detachEvent("onreadystatechange",arguments.callee),ma())}),document.documentElement.doScroll&&window==window.top&&function(){if(!La){try{document.documentElement.doScroll("left")}catch(a){setTimeout(arguments.callee,0);return}ma()}}());Jb(window,"load",ma)},ka="atgRecVisitorId",mb="atgPlatoStop",lb="eeExpKey",xa=function(a){return!a||a==""+n||/^-?\d+$/.test(a)},fc=function(){var a=
(u.get("xdVisitorId")||"").replace(/!\d+$/,"");if(a!=""+n)return a},J=function(a){a&&(u.set(ka,a,!0),gc=a);return O||u.get(ka)||gc},fb=function(a){a&&(u.set("atgRecSessionId",a),hc=a);return u.get("atgRecSessionId")||hc},tb=function(){if(Ia||0===Ia){var a=fc()||""+n;u.set("xdVisitorId",a.replace(/(!\d+)?$/,"!"+Ia),!0)}},kb=function(a){O=Ka()||fc();a&&(a.donotcall&&pb(),xa(O)&&((O=a.visitorId)?Sb(a):(O=a)&&J(a)));xa(O)||Ma();tb()},Sb=function(a){a&&(a.visitorId&&J(a.visitorId),a.sessionId&&fb(a.sessionId));
r.occur("tracking")},Na,Oa,cc=function(a){Oa=a;rb(a,1)},rb=function(a,b){b=1===b;if(B(a)){b||(Na=a);var c={};p(a,function(a,e){p(e.goals||[],function(a,d){/^ee[A-Z]/.test(d.name)||(d.val=d.name,d.name="eeCustomEvent");c[d.name]=b?xc:Pa})});delete c.eeAbStart;ab(c)}},yc=function(a){var b=a.id;na((a.exp?Oa:Na)||[],function(c){c.id==b&&(c.started=1,Pa({type:"eeAbStart"},{type:a.type,a:b,exp:a.exp}))})},xc=function(a,b){b.exp=1;Pa(a,b)},Pa=function(a,b){b=b||{};var c=a.type;/Offer|Accept/.test(c)&&!/On$/.test(b.link&&
b.link.logStatus||"")||p(b.exp?Oa:Na,function(a,e){!e.started||b.a&&b.a!=e.id||p(e.goals||[],function(a,d){c!=d.name||d.w&&d.w!=(b.id||b.linkid)||d.r&&d.r!=(b.rule&&b.rule.id)||d.val&&d.val!=b.data&&"eeCustomEvent"==c||(a={id:e.id,g:d.id,customVars:Qa()},b.a&&(a.type=b.type),Q("abEvent",{ab:a},b.exp))})})},ic={},dc=function(a){B(a)&&window.$&&$.Topic&&p(a,function(a,c){var b=c&&c.topicName;b&&!ic[b]&&($.Topic(b).subscribe(function(){c.expGoalIds&&c.expGoalIds.length&&p(c.expGoalIds,function(a,d){Q("ccEvent",
{t:"4",g:d.goalId,e:d.expId,d:[{n:"topic",v:b},{n:"topicId",v:c.topicId}],c:"NONE"},1)})}),ic[b]=1)})},vb=function(){var a,b={fade:function(a){var d=l.rules.faders,c=a.s+a.select;d[c]=d[c]||[];d[c].push(setTimeout(function(){a.d=a.d||a.h;var e=ya(a);!e||(d[c]||[]).length&&.1>N(e,"opacity")||Gb([e],{opacity:0},a.t||0,n,function(){a.j&&Y(a.j,"()");a.h&&b.showHide(a)})},a.d));l.rules.faders=d},displayPagePeek:function(a,b){L.enabled&&!L.active&&(L.active=1,L.host=zc(1)+("//"+(l.ESTARA_HOST||C.ESTARA_HOST||
"as00.estara.com")),a=function(){var a=l,b=a.cobrowse;a.pagepeek.launch=1;b&&K(b.uploadPP)&&b.uploadPP()},r.cond("eeAccepted")?a():r.wait({eeAccepted:!0},a),ha(ua("js/pp.js")))},runJavaScript:function(a,b){Y(a.callBack,"()")},loadJavaScript:function(a,b){a.url&&ha(a.url,n,la()||/^https:/i.test(a.url))},loadLegacyRules:Ac,rnSynProactiveChat:function(a,b){var d=a.rnJSON||{};d.type=2;a.divId=d.div_id=d.div_id||"myDiv";oa("ProactiveChat",d,b,a)},rnSynConditionalChatLink:function(a,b){var d=a.rnJSON||
{};d.type=7;d.info_element_id=d.info_element_id||"myChatLinkInfo";d.link_element_id=d.link_element_id||"myChatLink";d.container_element_id=d.container_element_id||"myChatLinkContainer";a.divId=[d.info_element_id,d.link_element_id,d.container_element_id];oa("ConditionalChatLink",d,b,a)},rnSynKnowledgeSyndication:function(a,b){var d=a.rnJSON||{};d.type=3;a.divId=d.div_id=d.div_id||"myDiv";oa("KnowledgeSyndication",d,b,a)},rnSynPollingSyndication:function(a,b){var d=a.rnJSON||{};V(d.survey_id)&&(d.type=
5,a.divId=d.div_id=d.div_id||"myDiv",oa("PollingSyndication",d,b,a))},rnCPProactiveChat:function(a,b){oa("ProactiveChat",a,b,a)},rnCPConditionalChatLink:function(a,b){oa("ConditionalChatLink",a,b,a)},showLink:function(){},stopProcessingRules:function(a,b){pa.clearAll();l.rules.page.stopProcessing=1},paramToJavaScriptVar:function(a,b){(b=jc(a.select))&&Y(a.value,"=",b)},populateCustomDataSegment:function(a,b){a:{var d=a.select;for(var c=(location.pathname+"//"+location.hash.slice(1)).split("/"),e=
0,m=c.length;e<m;e++)if(fa(c[e],d,"=")){d=c[e+1]||n;break a}d=void 0}d&&ca(a,d,b)},populateCustomDataURL:function(a,b){var d=jc(a.select);d&&ca(a,d,b)},populateCustomDataElementID:function(a,b){var d=Ra(a.select,1,1);d&&ca(a,d,b)},populateCustomDataElementName:function(a,b){var d=Ra(a.select,1);d&&ca(a,d,b)},populateCustomDataPage:function(a,b){var d=document.body;d=(d?d.innerHTML:"").match(T(a.select,a));var c=+a.multiResItem||0;d&&c<d.length&&ca(a,d[c],b)},populateCustomDataVar:function(a,b){var d=
Y(a.select);B(d)&&(d=1<=d.length?d[0]:null);ca(a,d,b)},populateCustomDataValue:function(a,b){ca(a,a.select,b)},hideInformationElementID:function(a,b){L.rules.push([a,"hide","id"])},hideInformationElementName:function(a,b){L.rules.push([a,"hide","name"])},maskInformationElementID:function(a,b){L.rules.push([a,"mask","id"])},maskInformationElementName:function(a,b){L.rules.push([a,"mask","name"])},chgClass:function(a){var b=ya(a),d=H(a.c.replace(/ +/g," "));if(b){if("="==a.a)var c=d;else c=" "+(b.className||
"").replace(/ +/g," ")+" ",p(d.split(" "),function(a,b){c=c.replace(" "+b+" "," ")}),"+"==a.a&&(c+=" "+d);b.className=H(c.replace(/ +/g," "))}},replaceA:function(b,c){var d=ya(b);d?p(b.value||{},function(a,b){"label"==a?d.innerHTML=b:"style"==a?d[a].cssText=b:("class"==a&&(a="className"),d[a]=b,d.setAttribute(a,b))}):a=c&&c.exp},replace:function(d,c){var e=ya(d),g=d.c||"",k=d.p;if(e){var m=e.outerHTML;if("r"==d.t)"O"==k?m&&(e.outerHTML=g):e.innerHTML="I"==k?g:e.innerHTML.replace(T(d.m),g);else if("W"==
k){if(m){if(d.e){var h=I[d.e](d.value);h.innerHTML=m;h=h.outerHTML}else h=g+m+(d.ca||"");e.outerHTML=h}}else if(/[AB]/.test(k))h=I.SPAN(),h.innerHTML=g,e.parentNode.insertBefore(h,/A/.test(k)?e.nextSibling:e),"AB"==k&&(d.p="B",b.replace(d,c));else try{"S"==k&&(h="afterbegin"),"E"==k&&(h="beforeend"),h&&e.insertAdjacentHTML(h,g)}catch(q){}}else a=c&&c.exp},showHide:function(b,c){var d=ya(b);d?b.d?N(d,{display:"none",visibility:"hidden"}):N(d,{display:"",visibility:"visible"}):a=c&&c.exp},logCustomEvent:function(a,
b){var c=Qa(),d="",e={};a=a.value;var m="TransactionCompleted"==a,h=m?a:"CustomEvent",q={customVars:c,data:a,rule:b};ub("ee"+h,q);Sa(R(h.charAt(0))+h.slice(1),q);if(z&&m){m={accountid:z,eventtype:a.slice(0,-1)};for(h=10;h;--h)m["var"+h]=c["var"+h];h=I.IMG({src:gb("//"+(l.ESTARA_HOST||C.ESTARA_HOST||"as00.estara.com")+"/webcare/webevents/webevent.php",m,1)})}p(c,function(a,b){t(b)&&(d+=a+":"+b+"&zwnj;#")});e[a]=d?{data:d}:{};Q("events",{events:e},b&&b.exp)},urlRedirect:function(a,b){a.url&&(document.location=
a.url)},suppressedShowLink:function(){}},c=function(a,c,f){var d=f&&f.exp;if(d||!M||1==M||M==location.href)if(b[a])b[a](c.args,f);else"abStart"==a?(d&&(c.exp=1),yc(c)):"abGoal"==a&&Pa({type:c.type},{rule:f,exp:d})};return{runActions:function(b,e){var d,g;try{p(b,function(b,f){g=b;a=0;d=f.name;c(d,f,e);a&&l.rules.retryActions.push({action:f,context:e})})}catch(k){k.message+=" ["+d+"/"+g+"]",P(k,"action",3,e,e&&e.exp)}},retryActions:function(){var b,e=0,f,g=[],k,m=l.rules;try{p(m.retryActions,function(d,
m){k=m.context;f=m.action;e=d;a=0;b=f.name;c(b,f,k);a&&g.push(m)}),m.retryActions=g}catch(h){m.retryActions.splice(e,1),h.message+=" ["+b+"/"+e+"]",P(h,"action",3,k,k&&k.exp)}}}}(),Bc=function(){var a;return{launch:function(b){aa(b)&&(a=b["poll-delay"],(a=t(a)?V(a):-1)&&ab(b))},pollDelay:a}}(),wb,Vb={push:function(a){a=a||{};var b=a.type||a.t,c=a.data||{};switch(b){case -1:c.currencyCode&&(wb=c.currencyCode);break;case 1:wb&&Q("ccEvent",{t:b,d:c,c:wb},1);break;case 2:c.data&&c.currencyCode&&Q("ccEvent",
{t:b,d:c.data,c:c.currencyCode},1);break;case 3:if(a.id&&a.v){Q("expEvent",{t:b,id:a.id,v:a.v,h:location.hash||n},1);if((b=a.pcm)||0===b)Ia=b,tb();u.set("eeA"+y,J()+":"+(a.a||""),a.a?744:-1)}}}},Dc=function(){var a="n2 i2 v2 nk ik vk n9 i9 p9 r9 v9 nr ir pr rr vr n8 i8 p8 r8 v8 n6 i6 p7 r7 v6 no io pp rp vo n21 i21 v21 nk1 ik1 vk1 n01 i01 v01 n11 i11 v11 n31 i31 v31 n41 i41 v41 n61 i61 v61 no1 io1 vo1 n8 i8 v8 n22 i22 v22 nk2 ik2 vk2 n32 i32 v32 n02 i02 v02 n52 i52 v52 nn2 in2 vn2 v23 va3 n21i n20f n20d i21i i20f i20d nk1i nk0f nk0d ik1i ik0f ik0d n90f n90d i90f i90d nrif nr0d ir0f ir0d n61i n60f n60d i61i i60f i60d no1i no0f no0d io1i io0f io0d n01i n01f n01d i01i i01f i01d n11i n11f n11d i11i i11f i11d n31i n31f n31d i31i i31f i31d n41i n41f n41d i41i i41f i41d n80i n80f n80d i80i i80f i80d n23c i23c nk3c ik3c vc2 vb2 ve2 vd2 v23 t21 tk1 t31 t01 t41 t11 N23A N23 Na3 N9 Nr N83 N6 No V2 Vk V9 Vr V8 V6 Vo V21 Vk1 V31 V41 V01 V11 V8 I23 I23 I23 I23 I23 I23 I23 I23 I23 I23 L23 L23l v2".split(" "),
b=function(a,b,e,f){var c=e.split(""),d=c[0];e=parseInt(c[1],36);b=17<e;e="< <= = > >= bt in pin r ~ ! +< +> -< ->".split(" ")[b?e-18:e];var m=+c[2]||0;c=c[3]||null;f=a.value;d=a.s||d;m=t(a.f)?a.f:m;a.o&&(b=/!/.test(a.o),e=a.o.replace("!",""));var h=Cc(d,m,a,e,c,b);if(3==m||"L"==d)f=!0;"N"==d&&(/in/.test(e)&&(f=h,h=a.value),"r"==e&&(e="="));if(!t(h)||!t(f)||!t(e))return"";1==m&&(c=Ta(h),h=a.p,1==w(c)?(h=Math.pow(10,h||0),h=V(c*h)/h):h=void 0);if("r"==d)return c=h,null==f&&"~"==e&&(f=""),B(f)||(f=
[f]),"r"==e&&(f=Ua(f,T,a)),a=kc(c,f,e,a),b?!a:a;if(2==m)if(/[+-]/.test(e)&&(/-/.test(e)&&(f=-f),e=e.slice(1),c=h,d=za,m=new Date,Va(m)?(m.setDate(m.getDate()+V(f)),f=m):f=null,h=d(f),f=c),"bt"==e){if(!B(f)||2!=f.length)return!1;f=Wa(f,2)}else f=za(f);"r"==e&&(f=T(f,a));return fa(h,f,e,b)};return{runConditions:function(c,d){if(!aa(c))return 0;d||(d={});var e={finalResult:0,groupResult:[]},f,g=c.conditions||[],k=c.operator||"and";if(!g.length)return 1;c=0;for(f=g.length;c<f;c++)t(g[c].name)||(g[c].name=
189),e.groupResult[c]=g[c].name+"@x";try{for(c=0,f=g.length;c<f;c++){var m=0,h=g[c];var q=h.name;t(h.result)?m=h.result:(0==w(q)&&(q=-1),h.track&&p(h.track.args,function(a,b){h.args[a]=b}),m=0<=q&&a[q]?b(h.args,d,a[q],h.name):0);e.groupResult[c]=q+"@"+(""===m?"!":Ta(m));e.finalResult=m||0;if("and"===k&&!m||"or"===k&&m)return e}}catch(A){A.message+=" ["+q+"/"+c+"]",P(A,"condition",3,d,d&&d.exp),e.finalResult=0}return e}}}(),Ja,nb,y,z,O,gc,hc,xb="",S="",L={rules:[]},wa=function(a){a&&(a=a.replace(/_[^_]*$/,
""));y=a;l.CFG.expid=a},ja=function(a){u.has(mb)&&(a=0);z=a;l.CFG.uoid=a;l.CFG.eeid=a;F&&(F.eeid=a);va&&ac()},lc=location.href,M,Aa,yb,mc=function(){lc!=location.href&&zb();yb=setTimeout(mc,300)},Ab=1,zb=function(){lc=location.href;tb();va?(l.rules.page.stopProcessing=1,pa.reset(),Bb(),p(Za,function(a,b){$a(b[0],b[1],b[2],b[3])}),Za=[],l.pagepeek=L={rules:[]},r.E={},r.B={},r.W=[],B(window._vsq)&&(_vsq=[]),Ba=ba=W=X=Oa=Na=n,nb=va=0,Ab&&Ma()):(Bb(),Ab&&ma())},Bb=function(){var a=l.rules;p(a.faders||
{},function(a,c){p(c||[],function(a,b){clearTimeout(b)})});a.faders={};a.retryActions=[];a.retryGoals=[];a.retryCount=0;a.retryTimer&&clearTimeout(a.retryTimer);a.ruleLog=[];a.eventLog=[];a.ruledata=[];a.rulehash=Xa={};a.page={startedAt:+new Date,tracker:{s:0,mouse:{type:"mousemove",state:0,x:0,y:0}},customVars:{},serverDelta:0};l.rules=a;window.eeExp&&eeExp.start()},ub=function(a,b){var c=l.rules,d=c.maxEventLog;c=c.eventLog;var e=+new Date;d&&(0<d&&c.length>=d&&c.shift(),c.push({ts:qa(e),browserTime:e,
event:a,data:b||{}}));r.occur(a,b)},ob=function(a){a=window.eStara_fsguid||nc("fs_nocache_guid")||a&&J()&&J().slice(0,50)||n;z&&(window.eStara_fsguid=a);return a},Ac=function(){},x=function(a,b){var c=l.CFG[a];a=C.CFG[a];return t(c)?c:t(a)?a:b},la=function(){return"s"==x("-eeFlag")||U},zc=function(a){var b=location.protocol;return la()&&!a?"https:":/file:/i.test(b)?"http:":b},Ec=function(a){var b=da("body")||da("html")||da("head");b&&b.appendChild(a)},oc=function(a){return K(a)||Kb&&!!a&&!t(a.toString)&&
/^\s*\bfunction\b/.test(a)},qa=function(a){return(+a||+new Date)+l.rules.page.serverDelta},t=function(a){return a!==n},Ua=function(a,b){var c=[],d=[].slice.call(arguments,1);p(a,function(a,f){d[0]=f;c[a]=b.apply(null,d)});return c},na=function(a,b){for(var c=[].slice.call(arguments,1),d=0,e=a.length;d<e;d++)if(c[0]=a[d],b.apply(null,c))return!0;return!1},Ra=function(a,b,c){c=c?"id":"name";a=eb(a,"*["+c+"]",c,{"case":1});return b?a[0]:a},da=function(a){return(ta(a)||[])[0]},Qb=function(a){var b=da("head")||
da("body")||da("html");b&&b.appendChild(a)},T=function(a,b){var c="",d="";if(6==w(a))return a;b||(b={});a=a.replace(/^\|/,"");if(a.match("^/")){var e=a.lastIndexOf("/")||a.length;d=R(a.slice(e));a=a.substr(1,e-1)}if(0===b["case"]||/i/.test(d))c="i";if(b.multi||/m/.test(d))c+="m";if(b.global||/g/.test(d))c+="g";return RegExp(a,c)},nc=function(a){if(0==w(a)){a=H(a);var b=u.get(a);return b?decodeURIComponent(b):u.has(a)?"":n}},Fc=function(a){var b=[];if(6==w(a)){var c=u.match(a)||{};p(c,function(a,e){c.hasOwnProperty(a)&&
b.push(a)})}return b},Y=function(a,b,c){var d=window,e,f=/'|"/,g=[],k,m,h,q,A,v,l=0,r=function(a,b){return b?a:"null"===a?null:isNaN(+a)?window[a]:+a},D=[],u=document,w=0,x="="==b,y=/[\\[().,"' ]|\]/g;a=t(a)?H(a+"").replace(/^window\./,"").replace(/;*$/,""):"";if(""!=a){for("()"==b&&/[^)]$/.test(a)&&(a+=b);y.exec(a);)b=y.lastIndex-1,b>w&&D.push(a.slice(w,b)),D.push(a.charAt(b)),w=b+1;w<a.length&&D.push(a.slice(w));a=D[0];var G=D.length-1;if("eval"==a)l=1;else if(0==G&&x)d[a]=c;else return d[a]&&(/\[native code\]/.test(d[a])&&
(u=d),"console"==a&&d.console&&(u=console)),p(D,function(a,b){if(d&&!l){if(A)e=t(e)?e+b:b,A=0;else if("\\"==b)A=1;else if(f.test(b)){v=0;if(q){b==q?(h&&(g.push(r(e,q)),e=n),q=0):e=t(e)?e+b:b;return}q=b}else q?e=t(e)?e+b:b:"."==b?k=1:"["==b?m=1:"("==b?h=1:","==b?(v&&g.push(n),v=1):a||(d=d[b]);!a||q||~"[(.,\"' \\".indexOf(b)||("]"==b?(a==G&&x?d[e]=c:d=d[e],m=0,e=n):")"==b?((t(e)||v)&&g.push(r(e,q)),oc(d)?(d=d.apply?d.apply(u,g):Function.prototype.apply.apply(d,[u,g]),u=document):l=1,g=[],v=h=0):k?(a==
G&&x?d[b]=c:d=d[b],k=0):m?e=r(b,q):h&&(g.push(r(b,q)),v=0))}}),l?n:d}},Cb=function(a){a=a.replace(/^ *body *>? */i,"");var b=document,c=b.body,d=/^([^:]+):eq\((\d*)\)/i,e=H(a).split(">"),f,g;a&&p(e,function(a,e){e=H(e);if(!a&&e.match(/^#/))c=b.getElementById(e.slice(1));else{if(f=e.match(d))e=f[1];g=[];c&&(p(c.children,function(a,b){b&&R(b.tagName||"")==R(e)&&g.push(b)}),c=f?g[V(f[2])||0]:g)}});return c?[].concat(c):[]},ya=function(a){var b=a.select,c="i"==a.s?"id":"name";return"c"==a.s?Cb(b)[0]:
(a=eb(a.regex?T(b,a):b,"*["+c+"]",c,a))&&0<=a.length?a[0]:a},Cc=function(a,b,c,d,e,f){f=c.select||"";var g=c.value,k=function(a,b){b||(b="");if(B(a))return a.length?Ua(a,k,b):void 0;if("c"==b)var c="radio"==a.type||"checkbox"==a.type?a.checked:null;else if(/[ifd]/.test(b)){if("select-one"!=a.type)return;c=a.selectedIndex;if(~c&&"i"!=b)return"f"==b?a[c].value:a[c].text}else{if(0==w(a.value))return a.value;if(0==w(a.innerHTML))return a.innerHTML}return c},m=function(a,b,c,d){if(b||!c){if(B(a))return Ua(a,
m,b,c,d);0!=w(a)&&(a=Z(a));b&&(a=H(a));"r"==d||c||(a=R(a))}return a};if("t"==a)return+new Date-l.rules.page.startedAt;if("r"==a)return document.body;if("a"==a)return(ba||{})[f];if("N"==a){if("A"==e){var h=u.has(ka);return g?h:!h}"r"!=d&&(c["case"]=c["case"]||0);if("="==d||"!"==d)return!!u.has(T("^"+g+"$",c));h=Fc("in"==d?/^/:T(g,c));h=m(h,c.trim,c["case"],d);return"in"==d?h:"r"==d?0<h.length:h.join()}if("V"==a)return h=nc(f),b?Wa(h,b):"r"==d||c["case"]?h:R(h);if("I"==a)return(h=l.rules.page.tracker[c.viname])?
!!h.state:n;if("L"==a)return"l"==e?Gc(f):Db(c);if("v"==a)h=Y(f),K(h)&&(h=h());else{if("p"==a)h=document.body;else if(/[inc]/.test(a)){h="c"==a?Cb(f)[0]:Ra(f,0,"i"==a);if(!h)return;1==h.length&&(h=h[0])}if(null==h)return null;h=k(h,e)}if(null!=h)return h=m(h,c.trim,c["case"],d),w(h)!=b&&(h=Wa(h,b)),h},Wa=function(a,b){return B(a)?Ua(a,Wa,b):1==b?Ta(a):2==b?za(a):3==b?pc(a):Z(a)},fa=function(a,b,c,d){null==a&&"~"==c&&(a="");if(B(a)&&"in"!=c)return a=na(a,fa,b,c||"="),d?!a:a;if(/in/.test(c)&&!B(b))return!1;
switch(c){case "!":return!a;case "=":a=a===b;break;case "<":return a<b;case "<=":return a<=b;case ">":return a>b;case ">=":return a>=b;case "r":return b?b.test(a):!1;case "~":a=!!~a.indexOf(b);break;case "in":a=hb(a,b);break;case "bt":a=a>=b[0]&&a<=b[1];break;case "pin":a=qc(b,a);break;default:return!1}return d?!a:a},kc=function(a,b,c,d){if(a){var e=a.childNodes.length,f=0,g;if(e)for(g=a.childNodes[f];g;){if(3==g.nodeType&&g.parentNode&&!g.parentNode.tagName.match(/^script$/i)){var k=g.nodeValue;
if("r"==c){if(na(b,function(a){return a.test(k)},k))return!0}else if(d["case"]||(k=R(k)),B(b)){if(qc(b,k))return!0}else if(k.match(b))return!0}if(kc(g,b,c,d))return!0;f++;g=f<e?a.childNodes[f]:null}}return!1},hb=function(a,b){return B(b)?B(a)?na(a,hb,b):na(b,function(b){return a===b},a):!1},qc=function(a,b){0!=w(b)&&(b=Z(b));return null==b?!1:na(a,function(a){return b.match(a)},b)},R=function(a){0!=w(a)&&(a=Z(a));if(null!=a)return a.toLowerCase()},Hc={String:0,Number:1,Date:2,Boolean:3,Function:4,
Object:5,RegExp:6,HTMLDocument:7,HTMLCollection:8,NodeList:9},w=function(a){a=bb.call(a).slice(8,-1);var b=Hc[a];return t(b)?b:/Element/.test(a)?10:n},aa=function(a){return"object"==typeof a},V=function(a){return parseInt(a,10)||0},Va=function(a){return 2==w(a)&&isFinite(+a)},za=function(a){var b=w(a);if(0==b)if(a.match(/^\d+$/))a=new Date(+a);else{a=a.match(/^(\d{1,4})\D(\d\d?)\D(\d\d?)$/);if(!a)return null;b=+a[3];var c=+a[2]-1;a=+a[1];100>a&&(a+=70>a?2E3:1900);a=new Date(a,c,b);if(a.getDate()!=
b)return null}else if(1==b)a=new Date(V(a));else{if(4==b)return za(a());if(2!=b)return null}if(!Va(a))return null;b=a.getDate();c=a.getMonth()+1;return a.getFullYear()+"-"+(10>c?"0"+c:c)+"-"+(10>b?"0"+b:b)},Ta=function(a){if(null!=a){switch(w(a)){case 0:a=parseFloat(a);break;case 2:return Va(a)?+a:null;case 3:return+a;case 4:return Ta(a())}return isNaN(a)?null:a}},Z=function(a){if(null!=a){switch(w(a)){case 0:return a;case 1:return isNaN(a)?null:a+"";case 2:return za(a);case 3:return a+"";case 4:return Z(a());
case 7:return a.innerHTML;case 8:case 9:return a.length?Z(a[0]):null;case 10:case 5:return t(a.value)?a.value:a.length?Z(a[0]):t(a.innerHTML)?a.innerHTML:null}return t(a.value)?a.value:t(a.toString)?a.toString():null}},pc=function(a){if(null!=a){var b=w(a);return 0==b?"1"===a||/^t(rue)?$/i.test(a):1==b?!isNaN(a)&&0<a:2==b?Va(a):3==b?a.valueOf():4==b?pc(a()):!!a}},ca=function(a,b,c){b=Z(b);if(null!=b){a.trim&&(b=H(b));a.rnvalue&&Sa("customData",{name:a.rnvalue,value:b,ruleid:c?c.id:""});a=a.value;
if(0!=w(a)||!/^(total(size|type)?|[fl]name|phone|email)$/.test(a)){a=V(a);if(1>a)return;a="var"+a}l.rules.page.customVars[a]=b;c&&c.exp||/^total/.test(a)||Y("eStara_"+a,"=",b)}},jc=function(a,b){t(b)||(b=location.href);a=RegExp("[\\?&]"+a+"=([^&#]*)").exec(b);return t(a)&&null!==a?decodeURIComponent(a[1].replace(/\+/g," ")):null},Ic=function(a,b){a=a[b.type]||[];var c=0;if(!t(b.timeframe))return a.length;p(a,function(a,e){fa(e,b.boundary,">")&&++c});return c},Gc=function(a){var b=l.rules.page,c=0;
"any-call"!=a&&(c+=(b.chats||0)+(b.ischats||0));"any-chat"!=a&&(c+=b.calls||0);return!!c},Jc=function(a){var b=a.type;var c=a.select,d="id name value src alt href title".split(" ")[b];if(7==b)return Cb(c);0==b&&(c=c.slice(1));1==b&&(c=c.slice(7,-1));b=2==b?"input[type=button],input[type=submit],input[type=reset]":"* *  img img a a".split(" ")[b]+"["+d+"]";a.compare=a.compare||"r";return eb("r"==a.compare?T(c,a):c,b,d,a)},Db=function(a){var b=a.freq||0,c=a.freqOp||">",d=a.not,e=a.select+"",f=[],g=
Eb.logs,k=0,m;a.boundary=qa(+new Date-(a.timeframe||0));/!/.test(c)&&(c=c.replace("!",""),d=!d);var h=/any(-ca|$)/.test(e),l=/any(-ch|$)/.test(e),A=/rn/.test(e);h||l||A?p(g,function(a,b){m=R(b.type)||"";(l&&/chat$/.test(m)||h&&"call"==m||A&&m==e)&&f.push(a)}):f=e.split(",");p(f,function(b,c){k+=Ic(g[c]||{},a)});b=fa(k,b,c);return d?!b:b},Kc=function(a){var b={freqOp:">=",type:"offered",select:"any"};if(a){var c=a.ruleMaxInvite;-1>c&&(c=n);if(t(c)&&~c){b.freq=c;var d=Db(b)&&"hiddenRule"}!d&&t(a.siteMaxInvite)&&
~c&&(b.freq=a.siteMaxInvite,d=Db(b)&&"hiddenSite")}return d},Qa=function(a){var b=l.rules.page.customVars;return t(a)?b[a]:b},Q=function(a,b,c){c=new Ha(2==c?tc:c?Pb:Fa,c);c.addResource(a,b);c.send(la())},P=function(a,b,c,d,e){try{c&1&&(a.from=b,ub("eeError",{error:a,rule:d||{},exp:e})),c&2&&document&&Q("error",{type:a.name||"?",message:l.REC_VERSION+"|"+a.message,from:b,ruleId:d&&d.id||0,ts:qa(),siteId:l.rules.page[e?"expSiteId":"siteId"]||0},e?2:0)}catch(f){}},Yb="eeDebugKey",Zb="eeDebugIP",Lc=
function(){var a=window.eeDebugger&&window.eeDebugger.reset;a&&K(a)?a():(a=ua("css/debugger.css"),a=I.LINK({rel:"stylesheet",href:gb(a),type:"text/css"}),Qb(a),ha(ua("js/debugger.js")))},oa=function(a,b,c,d){var e=b.type,f=d.divId,g=1,k;b[e?"module":"name"]=a;b.rule=c;ob(1);3!=e&&5!=e&&(b.suppress="suppressed"==d.state?d.message:Kc(d));t(f)&&(p(B(f)?f:[f],function(a,b){(g=g&&t(b)&&!Ra(b,1,1))&&(k=I.DIV({id:b},k||""))}),g&&Ec(k));Sa(e?"synWidget":"cpWidget",b)},Sa=function(a,b){var c=window._vsq;a&&
c&&oc(c.push)&&aa(b)&&(b.ts||(b.ts=+new Date),c.push([a,b]))},Mc=function(a){this.rule=a;this.name=a.properties.name;this.id=a.properties.id;this.exp=a.exp;this.properties=a.properties||{};this.maxRunCount=a.properties.maxRunCount||0;this.conditionGroup=a.conditionGroup||{};this.conditions=this.conditionGroup.conditions||[];this.actionGroup=a.actionGroup||{};this.trueActions=this.actionGroup.trueActions||[];this.falseActions=this.actionGroup.falseActions||[];this.runCount=this.scheduled=0;this.active=
1;this.triggers=a.triggers||[];this.runUntil=t(this.properties.until)?this.properties.until:-1;this.runRule=function(a){var b=l.rules;if(!this.exp){if(M&&1!=M&&M!=location.href)return 0;if(b.page.stopProcessing)return this.active=0}if(this.chained)return 1;if(!this.active)return 0;this.runCount++;a=1;var c=b.conditions.runConditions(this.conditionGroup,this),f=+new Date,g=c.finalResult,k=g?this.trueActions:this.falseActions,m=this.runUntil,h=b.maxRuleLog;b=b.ruleLog;this.lastEvaluation=!!g;this.lastEvaluationDetail=
c.groupResult;vb.runActions(k,this);h&&(0<h&&b.length>=h&&b.shift(),b.push({ts:qa(f),browserTime:f,id:this.id,ran:g}));r.occur("eeRuleRan",{source:this});this.maxRunCount&&this.runCount>=this.maxRunCount&&(a=0);~m&&!!m==!!g&&(a=0);return this.active=a};var b=[];p(this.conditions,function(a,d){d.args||(d.args={});a=d.args;var c="viname-"+l.rules.page.tracker.s++;if(d.track){var f=d.track.args||(d.track.args={});"mousemove"==f.name&&(a.viname=f.set="mouse");a.viname||(a.viname=f.set=c);b.push(d)}});
b.length&&(this.trackConditions=b)},Xa={},Ya=function(a,b){return function(){return a.apply(b,arguments)}},Nc=function(a,b,c){var d=b.args,e=d.after||0,f=d.times||0,g=d.wait||0,k=c||0,l=0,h=0,n=function(){l++;if(f&&h>=f)k&&r.unbind(d.name,n);else if(l>e){var b=function(){a.runRule.apply(a,arguments);h++};g?setTimeout(b,g):b()}};return n},pa=function(){var a=0,b={},c={},d=[],e=function(){return{rules:{},args:{},id:0,run:function(){for(var a in this.rules)this.rules.hasOwnProperty(a)&&(this.rules[a].runRule.apply(this.rules[a],
this.args[a]||[])||delete this.rules[a]);a:if(a=this.rules,aa(a)){for(b in a)if(a.hasOwnProperty(b)){var b=0;break a}b=1}else b=0;b&&(this.remove(),this.stop())},stop:function(){},remove:function(){delete this.scheduled[this.name]}}},f=function(){var a={},b,c,d,e=[],f=function(){var a=window,b=document||{},c=b.documentElement||0;if(t(c.clientWidth)&&c.clientWidth)return c.clientWidth;if(b.body)return b.body.clientWidth;if(t(a.innerWidth))return a.innerWidth},g=function(a){var b=a.region,c=a.set,d=
b.x,g=b.y,h=b.height,k=b.length;b=b.count;var m={id:"region:"+d+":"+g+":"+k+":"+h+":"+b,type:a.name,state:0,timestamp:[],count:0,x:d,y:g,zoneY:g+h,zoneX:~k?d+k:f()-2,limit:b,set:c,fire:a.fire||c};a.wait?(m.active=0,setTimeout(function(){m.active=1},a.wait)):m.active=1;c&&(l.rules.page.tracker[c]=m);e.push(m)},h=function(){try{p(a,function(b,c){var d=Y(b),e=l.rules.page.tracker[b]||{};c!=d&&(a[b]=d,e.state=1,e.old=c,e.current=d,r.occur("varchanged-"+b,{name:b,oldValue:c,newValue:d,tracker:e}))})}catch(G){P(G,
"track-var",0)}},k=function(a,b){var c=t(b.type)?Jc(b):ta(b.select);p(c,function(c,d){sa(d,b.name,function(b){a.count++;a.state=1;a.timestamp.push(+new Date);a.fire&&r.occur(a.fire,a)},b.select+"-"+c)});return c};sa(document,"mousemove",function(a){a||(a=window.event);var f=l.rules.page.tracker.mouse;f.y=d=a.clientY;f.x=c=a.clientX;f.state=1;if(b)for(a=0,f=e.length;a<f;a++){var g=e[a];g.active&&(!g.entered&&d<=g.zoneY&&c<=g.zoneX&&d>=g.y&&c>=g.x&&(g.entered=1),g.entered&&(d>g.zoneY||c>g.zoneX||d<
g.y||c<g.x)&&(g.entered=0,g.count++,g.timestamp.push(+new Date),g.count==g.limit&&(g.fire&&r.occur(g.fire,g),g.state=1,g.active=0)))}});return{reset:function(){a={};b=c=d=n;e=[]},addClickToEle:k,varchange:function(b,c){var d=l.rules.page;if(!a[b.name]){try{var e=Y(b.name)}catch(Oc){P(Oc,"track-var",3,c,c&&c.exp)}a[b.name]=e;d.tracker[b.name]={type:"varchange",name:b.name,state:0,current:e}}b.fire&&m(c,{run:"event",args:{name:"varchanged-"+b.name}});d.trackerid=d.trackerid||setInterval(h,300)},domevent:function(a,
c){if(a.fire){var d=1==a.fire?"event-"+l.rules.page.tracker.s++:a.fire;a.fire=d;m(c,{run:"event",args:{name:d}})}"mouseout"==a.name&&(g(a),b=1);if("click"==a.name){a.exp=c&&c.exp;c={type:a.name,state:0,count:0,timestamp:[]};d=l.rules;var e=d.page.tracker;c.set=a.set||"click-"+e.s++;c.fire=a.fire||c.set;c.set&&(e[c.set]=c);e=k(c,a);!a.exp||7!=a.type||e&&e.length||d.retryGoals.push({click:c,args:a})}},inactivity:function(a,b){var c=a.time||0,d={type:"timeout",time:c,state:0,fire:a.fire||0,set:a.set||
"inactivity-"+l.rules.page.tracker.s++},e=d.set,f=e;d.fire&&(f=1==a.fire?e:d.fire,m(b,{run:"event",args:{name:f}}));l.rules.page.tracker[e]=d;b={id:0,name:e,resetTimer:function(){this.id&&(clearTimeout(this.id),this.start())},stop:function(){this.id=0;d.mouseHandler&&$a(document,"mousemove",d.mouseHandler,this.name);d.keyboardHandler&&$a(document,"keydown",d.keyboardHandler,this.name)},start:function(){var a=this;this.id=d.state?0:setTimeout(function(){var b=l.rules.page.tracker[e]||{};b.state=1;
a.stop();l.erg.occur(f,b)},c)}};a.mousereset&&(b.mouseHandler=Ya(b.resetTimer,b),sa(document,"mousemove",b.mouseHandler,e));a.keyboardreset&&(b.keyboardHandler=Ya(b.resetTimer,b),sa(document,"keydown",b.keyboardHandler,e));b.start()}}}(),g=function(a,b){p(b,function(b,c){(b=f[c.type])&&b(c.args,a)})},k=function(){var a=l.rules,b=[],c;p(a.retryGoals,function(a,d){(c=f.addClickToEle(d.click,d.args))&&c.length||b.push(d)});a.retryGoals=b},m=function(f,g){var h=g.args||{},k=g.run,l=h.selector||h.select,
m=h.interval||h.period,n=a+"-"+m;if(/after|every/.test(k)){l="after"==k?c:b;var v=l[n];v||(v=e(),v.period=m);v.rules[k+(h.interval?"-"+h.interval:"")+"."+f.id]=f;v.scheduled=l;v.name=n;l[n]=v;"every"==k&&h.period&&d.push(f)}else"now"==k?d.push(f):"domevent"==k?p(ta(l),function(a,b){sa(b,h.name,h.after||h.times?Nc(f,g,!1):Ya(f.runRule,f))}):"event"==k&&r.bind(h.name,Ya(f.runRule,f),h.data||{})},h=function(){clearInterval(l.rules.page.trackerid);p(c,function(a,b){b.stop()});p(b,function(a,b){b.stop()});
c={};b={}},q=function(){var a=x("-retryMax",120),b=l.rules;if(!a||b.retryCount<a)if(b.retryCount++,b.retryGoals.length&&k(),b.retryActions.length&&vb.retryActions(),b.retryActions.length||b.retryGoals.length)b.retryTimer=setTimeout(q,x("-retryMS",50))};return{scheduleRule:function(a){if(!a.scheduled&&(a.scheduled=1,p(a.triggers,function(b,c){c.track?g(a,c.track):m(a,c)}),a.trackConditions)){var b=[];p(a.trackConditions,function(a,c){b.push(c.track)});g(a,b)}},clearAll:h,checkForRetries:q,start:function(){p(d,
function(a,b){b.runRule()});d=[];p(c,function(a,b){b.id||(b.id=setTimeout(function(){b.run();b.remove()},b.period),b.stop=function(){clearTimeout(b.id)})});p(b,function(a,b){b.id||(b.id=setInterval(function(){b.run()},b.period),b.stop=function(){clearInterval(b.id)})});a++},reset:function(){f.reset();a=0;d=[];h()}}}(),X,W,ba,Ba,Ka=function(){return(F=window.OracleUnifiedVisit)&&F.visitorId&&F.visitorId()||n},jb=function(){return(F=window.OracleUnifiedVisit)&&F.visitId&&F.visitId()||n},Rb=function(a){window.$&&
$.Topic&&$.Topic("experiment.rules.ran").publish({"for":a})},Pc=function(){var a=H(this.responseText),b=this.status;if(4==this.readyState&&(ba={},204!=b&&404!=b||ia(),(200==b||304==b)&&a))try{a=JSON.parse(a)||{},p(a.audienceMembership||[],function(a,b){ba[b]=!0}),ia()}catch(c){P(c,"audienceMembership",2,n,1)}},Qc=function(){var a=new XMLHttpRequest,b=u.get("oauth_token_secret-storefrontUI");a.open("GET","/ccstore/v1/audienceMembership?filter="+Ba,!0);b&&(b="Bearer "+b.replace(/^"|"$/g,""),a.setRequestHeader("Authorization",
b));a.setRequestHeader("Content-Type","application/json");a.onreadystatechange=Pc;a.send()},ia=function(){var a=l.rules,b=window;S=S||jb();if(!U||S)if(M&&1!=M&&M!=location.href&&(X=n),Aa&&1!=Aa&&Aa!=location.href&&(W=n),!(y&&!W||z&&!X||W&&!ba)){var c=[].concat(X||[],W||[]);p(c,function(b,c){b=new Mc(c);c.exp||(a.ruledata.push(b),Xa[b.id]=b);pa.scheduleRule(b)});X&&(b._vsq||(b._vsq=[]),Sa("rulesReady",{visitorId:J(),sessionId:S||xb,rn:1}));W=X=n;pa.start();Rb(location.href);y&&pa.checkForRetries();
a.page.debug&&Lc()}},ec=function(a){a=a||[];var b={},c,d;Ba=[];p(a,function(e,f){f&&(a[e].exp=1,f.conditionGroup&&p(f.conditionGroup.conditions||[],function(a,e){(c=e.args)&&"a"==c.s&&!t(e.result)&&(d=c.select,b[d]||(b[d]=1,Ba.push(d)))}))});Ba.length?Qc():ba={};W=a;sb(a,1)},sb=function(a,b){var c=b?Aa:M;c&&1!=c&&c!=location.href||(b||(X=a),xa(J())?(P({type:"badID",name:"visitorId",message:"invalid:"+J()},"loadRules",2),u.set(ka,"",-1)):ia())},bc=function(a){l.rules.page.expSiteId=a.id;qb(a,1)},qb=
function(a,b){var c=a.spa;b?Aa=c:M=c;c&&Mb("-eeSPA",1);x("-eeSPA")&&!U&&(yb=yb||setTimeout(mc,300));1!=b&&(b=l.rules,c=b.page,b.maxRuleLog=a.logRules||0,b.maxEventLog=a.logEvents||0,c.siteId=a.id,c.creation=a.creation,c.serverPageStart=a.pageStart,c.serverDelta=a.pageStart-c.startedAt,c.ppEnabled=L.enabled=a.ppEnabled||0,xb=a.sessionId||"",a.debug&&(c.debug=1,c.siteName=a.siteName,c.evalOrder=a.evalOrder,c.maxInvites=a.maxInvites,c.suppressInvites=a.suppressInvites,c.publishDate=a.publishDate,c.fqdnHost=
a.fqdnHost,c.port=a.port,c.resetRetailerTime=a.resetRetailerTime,c.jvmStartTime=a.jvmStartTime,c.currentPageURL=a.url,c.ipAddress=a.ipAddress,c.pageTitle=a.pageTitle,c.url=a.url,c.siteDebug=a.siteDebug,Ib=function(){var b=[].slice.call(arguments);Da.length>a.logEvents&&Da.shift();Da.push(b)}),l.rules.page=c)},$b=function(a){a=a||{};Eb.loadData(a.sessiondata)},pb=function(){u.set(mb,1);y&&(z=0,ia())},Eb=function(){return{loadData:function(a){this.logs=a||{}},logs:{},logInvite:function(a,b){var c=l.rules.page,
d=a.id||a.ulbid||0,e=this.logs[d]||{type:a.type||""},f=e.type||"",g={inviteId:d,ruleId:a.ruleid,siteId:c.siteId,status:b,type:f,timeStamp:a.timestamp||c.serverPageStart+(+new Date-l.rules.page.startedAt)};a.children&&(g.children=a.children);a={estaraFsGuid:ob(),customVars:Qa()};a.invite=g;Q("inviteEvent",a);"accepted"==b&&f&&(c[f+"s"]=++c[f+"s"]||1);/^offered/.test(b)&&(b="offered");e[b]||(e[b]=[]);e[b].push(qa());this.logs[d]=e}}}(),vc=function(a){for(var b="cb"+ +new Date;l[b];)b+=0;l[b]=a;return"ATGSvcs."+
b},l=window.ATGSvcs={CFG:C.CFG||{},visitorId:J,sessionId:fb,cfg:x,setCfg:Mb,setXD:kb,setUOID:ja,setEEID:ja,setEXPID:wa,ee:{cfg:x,keepAlive:function(){z&&Q("ping",{});y&&Q("ping",{},1)},logInvite:function(a){a||(a={});var b=""+a.state,c={offer:"eeOffered",accep:"eeAccepted",decli:"eeDeclined",hidde:"eeHidden",suppr:"eeSuppressed",close:"eeClosed"}[b.substr(0,5)];c&&a.id&&a.type&&a.ruleid&&(a.rule=Xa[a.ruleid],a.timestamp=qa(a.timestamp),Eb.logInvite(a,b),ub(c,a))},reset:zb,stopRules:function(){Ab=
0;zb()},enableLogView:function(a,b){u.set(Yb,a);u.set(Zb,b||"",b?n:-1);return"OK"}},debugLog:Da,erg:r,dom:I,Selector:ta,start:ma,RESTRequest:Ha,util:{each:p,makeRegExp:T,getStaticURL:ua,paramToURL:function(a,b){a=a.replace(/\?$/,"");(b=Ga(b))&&(a+=(~a.indexOf("?")?"&":"?")+b);return a},debug:Ib,css:N,animate:Gb},loadExpRules:ec,loadExpABTests:cc,loadExpTopics:dc,loadExpConfig:bc,visitIDsLoaded:function(){var a=Ka(),b=jb();a&&b&&(kb(a),u.set(ka,a,!0),S=b,Xb(),Wb(),l.start(),ia())},loadRules:sb,loadABTests:rb,
loadInvites:$b,loadConfig:qb,doNotCall:pb,eventSubscribe:ab,getCustomData:Qa,getSessionId:function(){return xb},getVisitId:function(){return S},pagepeek:L,rules:{ruleLog:[],eventLog:[],ruledata:[],rulehash:Xa,page:{},analytics:Bc,scheduler:pa,conditions:Dc,actions:vb},REC_VERSION:194};Bb();I.tags("A|BR|DIV|IMG|LI|P|SCRIPT|SPAN|UL|B|LINK");C.uoid&&ja(C.uoid);C.eeid&&ja(C.eeid);C.expid&&wa(C.expid);var U=!!da("html#oracle-cc");db||wc();/[?;&]eeExpLoad=(\d+)/.test(location.search)&&u.set(lb,RegExp.$1);
if(u.has(lb))try{window.self!==window.top&&(Ja=1)}catch(a){Ja=1}}})();
